name: Push Stage version to DockerHub
on:
  push:
    branches:
      - 'dev'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Cut commit sha
        id: cut
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        
      - name: Log into DockerHUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCHUB_USERNAME }}
          password: ${{ secrets.DOCHUB_TOKEN }}
          
      - name: Build and push Docker image
        run: |
          docker build -f ./docker/Dockerfile -t ${{ vars.DOCHUB_USERNAME }}/var_keeper:${{ steps.cut.outputs.sha_short }} .
          docker push ${{ vars.DOCHUB_USERNAME }}/var_keeper:${{ steps.cut.outputs.sha_short }}
